# Generated by Django 5.2.4 on 2025-07-28 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_payment_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="currency",
            field=models.CharField(
                choices=[
                    ("KES", "Kenyan Shilling"),
                    ("USD", "US Dollar"),
                    ("EUR", "Euro"),
                ],
                default="KES",
                max_length=3,
            ),
        ),
    ]
