# Generated by Django 5.2.4 on 2025-07-28 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_alter_payment_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="payee",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="payee",
            name="id_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="payee",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="payee",
            name="postal_address",
            field=models.TextField(blank=True, null=True),
        ),
    ]
