# Generated by Django 5.2.4 on 2025-07-28 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0005_alter_payment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="payee",
            name="loan_limit",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="payee",
            name="savings_balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
