# Generated by Django 5.2.4 on 2025-07-28 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0006_payee_loan_limit_payee_savings_balance"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="mpesa_account_reference",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="mpesa_paybill_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="mpesa_phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="mpesa_till_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("Card", "Card"),
                    ("B2C", "B2C (M-Pesa)"),
                    ("LipaNaMpesaTill", "Lipa na M-Pesa (Till)"),
                    ("LipaNaMpesaPaybill", "Lipa na M-Pesa (Paybill)"),
                ],
                default="Card",
                max_length=20,
            ),
        ),
    ]
