# Generated by Django 5.2.4 on 2025-07-28 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0007_payment_mpesa_account_reference_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="scheduled_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
