# Generated by Django 5.2.4 on 2025-07-28 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0008_payment_scheduled_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Completed", "Completed"),
                    ("Failed", "Failed"),
                    ("Scheduled", "Scheduled"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
